### ISSUE TITLE
Please allow me to shoot golden crops with Create’s potato cannon.

### ISSUE THREAD

**Issue by tankplanelaserkoala** [Accieo/Midas-Hunger#10]
What if you could shoot golden crops with a potato cannon? Below are the crops that can be shot with a potato cannon and the golden versions that cannot be shot.

![image](https://github.com/Accieo/midas-hunger/assets/157739795/2aacbea0-1064-4e14-8cce-a7a7a844e9f1)

**Comment by Accieo** [comment]
Thanks for the feature request! It's been implemented in commit 9c9707c. I'll upload to curseforge and modrinth in the next few minutes.
