### ISSUE TITLE
Bug: [Fabric 1.21.1] Midas Foods are uncraftable

### ISSUE THREAD

**Issue by Greenknight9000** [Accieo/Midas-Hunger#17]
**Describe the bug**
When using the mod in Fabric 1.21.1, all Midas Foods are uncraftable

**To Reproduce**
Use Minecraft Fabric 1.21.1 and any recipe viewer mod, and you will see that it doesn't turn up any recipe results.

**Expected behavior**
The Midas Foods are able to be crafted when given the right crafting ingredients. 

**Screenshots**
Here, I am trying to craft a Golden Beetroot, yet it gives no output
![2024-12-19_19 49 44](https://github.com/user-attachments/assets/062f2e58-b23c-46fc-896d-f33d8972f32c)

**Comment by Accieo** [comment]
Thanks a lot for taking the time to create an issue. Fixed in 6e060e1. 

I'll be releasing the fix shortly on CurseForge and Modrinth.
