### ISSUE TITLE
Translation: <French>

### ISSUE THREAD

**Issue by Mozork01** [Accieo/Midas-Hunger#9]
{
  "item.midashunger.dried_golden_kelp": "Algue dorée séchée",
  "item.midashunger.cooked_golden_salmon": "Saumon doré cuit",
  "item.midashunger.cooked_golden_cod": "Morue dorée cuite",
  "item.midashunger.golden_turtle_egg": "Œuf de tortue doré",
  "item.midashunger.cooked_golden_chicken": "Poulet doré cuit",
  "item.midashunger.golden_beetroot": "Betterave dorée",
  "item.midashunger.golden_beetroot_soup": "Soupe de betterave dorée",
  "item.midashunger.sweet_golden_berries": "Baies dorées sucrées",
  "item.midashunger.golden_chorus_fruit": "Fruit du chorus doré",
  "item.midashunger.poisonous_golden_potato": "Pomme de terre dorée empoisonnée",
  "item.midashunger.baked_golden_potato": "Pomme de terre dorée cuite",
  "item.midashunger.cooked_golden_mutton": "Mouton doré cuit",
  "item.midashunger.cooked_golden_porkchop": "Côtelette de porc dorée cuite",
  "item.midashunger.cooked_golden_rabbit": "Lapin doré cuit",
  "item.midashunger.cooked_golden_beef": "Bœuf doré cuit",
  "item.midashunger.golden_pumpkin_pie": "Tarte à la citrouille dorée",
  "item.midashunger.golden_kelp": "Algue dorée",
  "item.midashunger.golden_beetroot_seeds": "Graines de betterave dorée",
  "item.midashunger.enchanted_golden_carrot": "Carotte dorée enchantée",
  "block.midashunger.sweet_golden_berry_bush": "Buisson de baies dorées sucrées",
  "block.midashunger.dried_golden_kelp_block": "Bloc d'algue dorée séchée",
  "block.midashunger.golden_kelp": "Algue dorée",
  "block.midashunger.golden_kelp_plant": "Plante d'algue dorée"
}

**Comment by Accieo** [comment]
Translation added, thanks!
